### ISSUE TITLE
.has-border.. doesn't work as expected

### ISSUE THREAD

**Issue by fherryfherry** [jmaczan/bulma-helpers#31]
Hello,

I use `.has-border-width-1` is does not showing anything. I don't know if I'm wrong how to use that class.

your class produce the bellow only : 
```css
.has-border-width-1 {
border-bottom-width: 1px!important;
}
```
If the class should be like bellow, it works for me : 
```css
.has-border-width-1 {
border-top-width: 0;
border-left-width: 0;
border-right-width: 0;
border-bottom-width: 1px!important;
border-style: solid;
}
```
Correct me if I wrong
